title: Samsudeen Bankole
#logo: /asset/img/headshot_circle.png
logo: Intl Passport Photograph_Circle.jpeg
#description: Machine Learning Engineer | Data Scientist
#show_downloads: true
theme: jekyll-theme-minimal
